[project]
name = "real-time-bitcoin-quarto-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "quarto>=0.1.0",
    "requests>=2.32.3",
]
